name: Unit Tests, Beta Toolchain

on:
  push:
    branches: main
  pull_request:

jobs:
  unit-tests-beta:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Beta Unit Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Install the latest beta Rust toolchain
        uses: dtolnay/rust-toolchain@beta
      - name: Run unit tests
        run: cargo test
