name: rustfmt Checks

on:
  push:
    branches: main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt-checks:
    runs-on: ubuntu-latest
    name: rustfmt checks
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Install the latest stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run rustfmt check
        run: cargo fmt --all --check
