name: rustfmt Check

on:
  push:
    branches: main
  pull_request:

jobs:
  rustfmt-check:
    runs-on: ubuntu-latest
    name: Check Rust source file formatting with rustfmt
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Install the latest stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run rustfmt check
        run: cargo fmt --all --check
